namespace Game.Enums
{
    public enum StatOptionCategory
    {
        PhysicalAttack,
        MagicalAttack,
        Strength,
        Intelligence,
        Constitution,
        Spirit,
        AttackSpeed,
        CastSpeed,
        MoveSpeed,
        MaxHealth,
        MaxMana,
        PhysicalDefence,
        MagicalDefence,
        Hit,
        Dodge,
        PhysicalCritical,
        MagicalCritical,
        EnhanceFire,
        EnhanceWater,
        EnhanceLight,
        EnhanceDark,
        ResistFire,
        ResistWater,
        ResistLight,
        ResistDark,
        DamageMultiplier,
        AdditionalGoldDropRate,
        AdditionalGoodRarityDropRate,
        AdditionalEqupmentDropRate,
        AdditionalMaterialDropRate
    }
}